version: "3.8"

services:
    web:
        image: apache_image
        container_name: silapor_webserver
        ports:
            - "80:80"
        volumes:
            - D:/Coding/Web/silapor:/var/www/html
        networks:
            - silapor_net
        depends_on:
            - db

    db:
        image: mysql:latest
        container_name: silapor_db
        environment:
            MYSQL_HOST: host.docker.internal
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: silapor
            MYSQL_USER: silapor
            MYSQL_PASSWORD: silapor
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
            - "3306:3306"
        volumes:
            - silapor_db:/var/lib/mysql
        networks:
            - silapor_net

networks:
    silapor_net:
        driver: bridge

volumes:
    silapor_db:
        driver: local
